version: "3"

services:
  postgres:
    image: "postgres:9.6.8-alpine"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      POSTGRES_DB: 'test_task_for_robotvera'
      POSTGRES_USER: 'test_task_for_robotvera'
      POSTGRES_PASSWORD: ''
      POSTGRES_HOST: 'postgres'
      POSTGRES_PORT: 5432

  backend:
    restart: always
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - "8000:8000"
    command: 'python -Wd /code/manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/code
    depends_on:
      - postgres
    networks:
      - backend
networks:
  backend:
volumes:
  pgdata: