# Generated by Django 2.0.6 on 2018-06-26 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='children/%Y/%m/%d/', verbose_name='Фотография')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('gender', models.CharField(choices=[('boy', 'Мальчик'), ('girl', 'Девочка')], max_length=4, verbose_name='Пол')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('classroom', models.SmallIntegerField(blank=True, null=True, verbose_name='Класс')),
                ('is_pupil', models.BooleanField(db_index=True, default=False, verbose_name='Учится')),
            ],
            options={
                'verbose_name': 'Ребенок',
                'verbose_name_plural': 'Дети',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_come', models.TimeField(db_index=True, verbose_name='Время прихода')),
                ('timestamp_away', models.TimeField(blank=True, db_index=True, null=True, verbose_name='Время ухода')),
                ('people_come', models.CharField(choices=[('dad', 'Папа'), ('mom', 'Мама')], max_length=3, verbose_name='Кто привел ребенка')),
                ('people_away', models.CharField(blank=True, choices=[('dad', 'Папа'), ('mom', 'Мама')], max_length=3, verbose_name='Кто забрал ребенка')),
                ('datestamp', models.DateField(db_index=True, verbose_name='Дата записи')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creche.Child', verbose_name='Ребенок')),
            ],
            options={
                'verbose_name': 'Запись в журнале',
                'verbose_name_plural': 'Записи в журнале',
            },
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together={('child', 'datestamp')},
        ),
    ]
